android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=-Xms1024m -Xmx4096M \
--add-exports=java.base/sun.nio.ch=ALL-UNNAMED \
--add-opens=java.base/java.lang=ALL-UNNAMED \
--add-opens=java.base/java.lang.reflect=ALL-UNNAMED \
--add-opens=java.base/java.io=ALL-UNNAMED \
--add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED
# Flutter 迁移工具自动添加的 Built-in Kotlin 兼容开关。
android.builtInKotlin=false
# Flutter 迁移工具自动添加的新 DSL 兼容开关。
android.newDsl=false
